# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 80
    onOpen: ignore
    visibility: public

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: magento
    command: |
      echo "MAGENTO_URL=$(gp url 80)" >> .env.local
      cd docker
      docker-compose up
      docker exec -it magento install-magento
      docker exec -it magento install-sampledata
